# Generated by Django 4.1.2 on 2022-10-16 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_alter_project_state'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('borrador', 'Borrador'), ('asignada', 'Asignada'), ('suspendida', 'Suspendida'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('description', models.TextField()),
                ('weight', models.IntegerField()),
                ('estimated_time', models.FloatField()),
                ('total_time', models.FloatField()),
                ('sprint', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
        ),
    ]
