# Generated by Django 4.1.2 on 2022-10-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_progreso', 'En Progreso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=20),
        ),
    ]
