# Generated by Django 4.1.2 on 2022-10-16 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_stories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('borrador', 'Borrador'), ('asignada', 'Asignada'), ('suspendida', 'Suspendida'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('description', models.TextField()),
                ('invested_time', models.FloatField()),
                ('estimated_time', models.FloatField()),
                ('remaining_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('user_story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_stories.userstories')),
            ],
        ),
    ]
